name: studyo_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.1.0
  dio: ^4.0.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  intl: ^0.18.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Georama
      fonts:
        - asset: assets/fonts/Georama-Thin.ttf
        - asset: assets/fonts/Georama-Light.ttf
        - asset: assets/fonts/Georama-Regular.ttf
        - asset: assets/fonts/Georama-Medium.ttf
        - asset: assets/fonts/Georama-SemiBold.ttf
        - asset: assets/fonts/Georama-Bold.ttf
        - asset: assets/fonts/Georama-ExtraBold.ttf
